name: CI

on:
  push:
    branches: [ "main" ]
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  
jobs:
  
  build:
    env:
      platform:
      region:
      account: 123456789012  

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: "Mostrar mensaje"
       run: echo "Hola mundo"

     - name: "Mostrando variables de entorno"
       run: |
           echo " Esto es el valor de plataform: ${{ env.platform }}"
           echo " Esto es el valor de region: ${{ env.region }}"
           echo " Esto es el valor de account: ${{ env.account }}"

    